version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  application:
    image: print-lab
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - postgres
      - redis
      - kafka

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,INTERNAL://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,INTERNAL://kafka:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
        - kafka_data:/var/lib/kafka/data


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - kafka-net
    ports:
      - "8089:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'

  postgres:
    image: postgres:16-alpine
    container_name: print-lab
    restart: unless-stopped
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPass
      POSTGRES_DB: print-lab
    ports:
      - "5432:5432"
    volumes:
      - print_lab_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-print-lab
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_print_lab_data:/data
    command: redis-server --timeout 2000

volumes:
  print_lab_data:
    name: postgres_print_lab_data
  redis_print_lab_data:
    name: redis_print_lab_data_data
  kafka_data:
      driver: local
